#Browser name
browser =chrome

#url
demourl = https://demoblaze.com/

#user data
demousername = saleemahamed
demopassword1 = saleem@1234

userlogin_Ecepwelcomemsg = Welcome saleemahamed

fillname = Saleem
country =India
city = chennai
creditcard = 2345 6754 9348 2345
month = 12/28
year = 2027

extendstart = C:\\Users\\abdul.saleem\\OneDrive - HTC Global Services, Inc\\Selenium Java\\SeleniumJavaClass\\DemoBlaze\\Reports\\index.html
extendend = C:\\Users\\abdul.saleem\\OneDrive - HTC Global Services, Inc\\Selenium Java\\SeleniumJavaClass\\DemoBlaze\\Reports\\index.html
